export enum ERoomTypes {
  BATHROOM = 'BATHROOM',
  COMBINED_BATHROOM = 'COMBINED_BATHROOM',
  TOILET = 'TOILET',
  KITCHEN = 'KITCHEN',
  CORRIDOR = 'CORRIDOR',
  VERANDA = 'VERANDA',
  FACADE = 'FACADE'
}
